import {sfxForCue,backgroundFor,counterProfile} from './visuals.js';
import {screenLabel,actionDuration} from './screen-actions.js';
const $=id=>document.getElementById(id), channel=new BroadcastChannel('big-hack-stage-v1');
const show=await fetch('show.json').then(r=>r.json());
let overrides=await fetch('overrides.json').then(r=>r.ok?r.json():{}).catch(()=>({}));
let saved;try{saved=JSON.parse(localStorage.getItem('big-hack-cue')||'null')}catch{}
let state={index:Math.max(0,show.cues.findIndex(c=>c.id===saved?.id)),running:false,blackout:false,serial:0,elapsed:0,screenBase:{left:0,right:0},anchor:Date.now(),volume:.85};
// This is a playback-session identifier, not an authentication token.
// randomUUID requires HTTPS or localhost; getRandomValues also works on LAN HTTP.
function controllerId(){
 const crypto=globalThis.crypto;
 if(typeof crypto?.randomUUID==='function')return crypto.randomUUID();
 if(typeof crypto?.getRandomValues==='function')return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
 return 'stage-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
}
let audio=new Audio(),sfx=[],elapsedShow=0,timerStart=0,lastScene='',lastRail='',lastAudio='',heartbeat={},notesSize=Number(localStorage.getItem('big-hack-notes-size')||27),controller=controllerId();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cue=()=>show.cues[state.index];
const elapsed=()=>state.elapsed+(state.running?(Date.now()-state.anchor)/1000:0);
function payload(){const profile=counterProfile(cue());return {...state,controller,audioTime:audio.currentTime||0,audioDuration:Number.isFinite(audio.duration)?audio.duration:(cue().audioDuration||0),counterValue:Math.floor((state.counterBase??profile.base)+elapsed()*profile.rate),screenElapsed:Object.fromEntries(['left','right'].map(side=>[side,(state.screenBase[side]||0)+elapsed()])),elapsed:elapsed(),sentAt:Date.now(),cue:{...cue(),isSpeaking:state.running&&!state.blackout&&!audio.paused&&!audio.ended&&!!audio.getAttribute('src')},override:overrides[cue().id]||{}}}
function broadcast(){channel.postMessage({type:'state',state:payload()});localStorage.setItem('big-hack-cue',JSON.stringify({id:cue().id}))}
function status(text,error=false){$('audioStatus').textContent=text;$('audioStatus').classList.toggle('error',error)}
function stopAudio(){audio.pause();audio.removeAttribute('src');audio.load();for(const a of sfx){a.pause();a.removeAttribute('src');a.load()}sfx=[]}
function audioPath(c,o){if(o.audioSource==='none')return null;if(['left','right'].includes(o.audioSource))return o[o.audioSource]?.src;return c.audio}
async function startAudio(restart=false){
 const serial=state.serial,c=cue(),o=overrides[c.id]||{},src=audioPath(c,o);
 if(restart){stopAudio();lastAudio=src||'';if(src){audio.src=src;audio.preload='auto';audio.volume=state.volume;audio.onplaying=()=>{if(serial===state.serial)broadcast()};audio.onended=()=>{if(serial===state.serial){status('Holding · GO when ready');broadcast()}};audio.onerror=()=>{if(serial===state.serial)status('Audio unavailable',true)}}
  for(const item of sfxForCue(c)){const a=new Audio('assets/sfx/'+item.id+'.mp3');a.loop=!!item.loop;a.volume=state.volume*(item.level??.35);a.dataset.level=item.level??.35;sfx.push(a)}
 }
 if(!state.running)return;
 const play=async a=>{try{await a.play()}catch(e){if(serial===state.serial&&e.name!=='AbortError')status('Press Start cue to enable audio',true)}};
 if(src&&!audio.ended){status('Playing '+(o.audioSource&&o.audioSource!=='tts'?'clip':c.name));await play(audio)}else status(c.kind==='live'?'LIVE · waiting for GO':'Holding · waiting for GO');
 for(const a of sfx)if(!a.ended||a.loop)play(a);
}
function navigate(index,run=state.running){const previous=payload();const previousCounter=previous.counterValue;const next=show.cues[Math.max(0,Math.min(index,show.cues.length-1))];const adjacent=index===(cue().groupEnd??state.index)+1;state.screenBase=Object.fromEntries(['left','right'].map(side=>[side,adjacent&&next.screenActions?.[side]&&next.screenActions[side]===cue().screenActions?.[side]?previous.screenElapsed[side]:0]));const nextCue=show.cues[Math.max(0,Math.min(index,show.cues.length-1))];state.counterBase=index>state.index?Math.max(counterProfile(nextCue).base,previousCounter):counterProfile(nextCue).base;state.elapsed=0;state.anchor=Date.now();state.index=Math.max(0,Math.min(index,show.cues.length-1));state.serial++;state.running=run;state.blackout=false;render();startAudio(true);broadcast()}
function toggle(){if(state.running){state.elapsed=elapsed();state.running=false;audio.pause();sfx.forEach(a=>a.pause())}else{state.running=true;state.anchor=Date.now();if(!timerStart)timerStart=Date.now();startAudio(!lastAudio&&!sfx.length)}renderTransport();broadcast()}
function blackout(){state.blackout=!state.blackout;if(state.blackout){state.elapsed=elapsed();state.running=false;audio.pause();sfx.forEach(a=>a.pause())}renderTransport();broadcast()}
function renderTransport(){$('play').innerHTML=(state.running?'Pause':'Start / Resume')+' <kbd>Space</kbd>';$('blackout').classList.toggle('active',state.blackout);$('blackout').textContent=state.blackout?'Restore displays (B)':'Blackout (B)'}
function render(){const c=cue(),s=show.scenes.find(s=>s.id===c.scene);document.documentElement.style.setProperty('--notes-size',notesSize+'px');$('sceneLabel').textContent='MOVEMENT '+s.movement+' / '+s.id.toUpperCase();$('sceneTitle').textContent=s.title;$('cueNumber').textContent=`${show.performanceStarts.filter(i=>i<=state.index).length} / ${show.performanceStarts.length}`;$('cueKind').textContent=c.kind==='live'?'LIVE ACTOR · HOLD FOR GO':c.kind==='voice'?(c.speaker==='narrator'?'NARRATION · PLAYS ONCE':'RECORDED LINE · PLAYS ONCE'):'STAGE / VISUAL CUE · HOLD FOR GO';$('cueId').textContent=c.id;$('speaker').textContent=c.name||'STAGE';$('lineText').textContent=c.notes?.map(n=>n.kind==='stage'?'('+n.text+')':(n.direction?'('+n.direction+')\n':'')+n.text).join('\n\n')||c.text;$('direction').textContent=c.direction;$('adaptation').textContent=c.stageAdaptation||'';$('screenNotes').hidden=!c.screenNotes;$('screenNotes').textContent=c.screenNotes?c.screenNotes+'\n\n'+Object.entries(c.screenActions).map(([side,id])=>side.toUpperCase()+': '+actionDuration(id).toFixed(1)+' seconds, then hold until GO.').join(' · '):'';$('sourceDirection').hidden=!c.sourceText;$('sourceDirectionText').textContent=c.sourceText||'';$('leftLabel').textContent=screenLabel(c,'left')||c.state.replaceAll('-',' ');$('rightLabel').textContent=screenLabel(c,'right')||(c.offstage?'BLACK / OFFSTAGE':c.staging?.view==='physical'?c.staging.location:c.name||c.mode);const n=show.cues[(c.groupEnd??state.index)+1];$('nextText').innerHTML=n?`<strong>${esc(n.name||'STAGE')} · ${esc(n.id)}</strong>${esc(n.text)}`:'End of show';
 if(lastScene!==c.scene){lastScene=c.scene;renderScenes();renderRail()}
 document.querySelectorAll('.cueItem').forEach(b=>b.classList.toggle('active',Number(b.dataset.index)===state.index));const active=document.querySelector('.cueItem.active');if(active)active.scrollIntoView({block:'nearest'});
 const o=overrides[c.id]||{};$('audioSource').value=o.audioSource||'tts';$('videoBehavior').value=o.behavior||'loop';$('loopStart').value=o.loopStart||0;$('editStatus').textContent=[o.left?.src&&'Left clip saved',o.right?.src&&'Right clip saved'].filter(Boolean).join(' · ');renderTransport();
}
function renderScenes(){let movement='';$('sceneList').innerHTML=show.scenes.map(s=>{let label='';if(s.movement!==movement){movement=s.movement;label=`<div class="movement">MOVEMENT ${movement}</div>`}return label+`<button class="sceneButton ${s.id===cue().scene?'active':''}" data-index="${s.start}"><span class="num">${s.id.slice(1)}</span><span>${esc(s.title)}</span></button>`}).join('');$('sceneCount').textContent=show.scenes.length}
function renderRail(){const query=$('search').value.trim().toLowerCase();$('cueList').innerHTML=show.cues.map((c,i)=>({c,i})).filter(({c,i})=>query?(c.text+' '+c.name+' '+c.scene).toLowerCase().includes(query):c.scene===cue().scene&&show.performanceStarts.includes(i)).map(({c,i})=>`<button class="cueItem ${state.index===i?'active':''}" data-index="${i}"><small>${esc(c.id)} · ${esc(c.name||'STAGE')}</small><p>${esc(c.text)}</p></button>`).join('')}
$('sceneList').onclick=$('cueList').onclick=e=>{const b=e.target.closest('[data-index]');if(b)navigate(Number(b.dataset.index),false)};
$('search').oninput=renderRail;$('go').onclick=()=>{if((cue().groupEnd??state.index)>=show.cues.length-1){blackout();status('End of show');return}if(!timerStart)timerStart=Date.now();navigate((cue().groupEnd??state.index)+1,true)};$('previous').onclick=()=>navigate(show.performanceStarts.filter(i=>i<state.index).at(-1)??0,false);$('play').onclick=toggle;$('replay').onclick=()=>navigate(state.index,true);$('blackout').onclick=blackout;
$('volume').oninput=e=>{state.volume=Number(e.target.value);audio.volume=state.volume;sfx.forEach(a=>a.volume=state.volume*Number(a.dataset.level||.35));broadcast()};
for(const delta of [-2,2])$(delta<0?'notesSmaller':'notesLarger').onclick=()=>{notesSize=Math.max(18,Math.min(48,notesSize+delta));localStorage.setItem('big-hack-notes-size',notesSize);render()};
for(const side of ['left','right']){const name=side[0].toUpperCase()+side.slice(1);$('open'+name).onclick=()=>{const w=window.open('display.html?side='+side,'big-hack-'+side,'popup,width=1280,height=720');if(!w)status('Allow popups to open display',true)};$(side+'File').onchange=async e=>{const file=e.target.files[0];if(!file)return;const id=cue().id;$('editStatus').textContent='Saving clip…';try{const r=await fetch(`/api/clip?cue=${encodeURIComponent(id)}&side=${side}&ext=${encodeURIComponent(file.name.split('.').pop())}`,{method:'POST',headers:{'Content-Type':file.type},body:file});if(!r.ok)throw Error(await r.text());const d=await r.json();overrides=d;render();broadcast();status('Clip saved')}catch(err){$('editStatus').textContent=err.message}e.target.value=''}}
async function saveOverride(reset=false){const id=cue().id,data=reset?null:{...(overrides[id]||{}),audioSource:$('audioSource').value,behavior:$('videoBehavior').value,loopStart:Math.max(0,Number($('loopStart').value)||0)};try{const r=await fetch('/api/cue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,value:data})});if(!r.ok)throw Error(await r.text());overrides=await r.json();navigate(state.index,false);$('editStatus').textContent='Saved'}catch(e){$('editStatus').textContent=e.message}}
$('saveCue').onclick=()=>saveOverride();$('resetCue').onclick=()=>saveOverride(true);
$('exportCues').onclick=()=>{const text=show.cues.map(c=>`${c.id}\t${c.scene}\t${c.kind}\t${c.name}\t${c.state}\t${c.text.replaceAll('\t',' ')}\t${c.direction}\t${(c.sourceText||'').replaceAll('\t',' ')}\t${[screenLabel(c,'left'),screenLabel(c,'right')].join(' / ')}\t${(c.screenNotes||'').replaceAll('\t',' ').replaceAll('\n',' ')}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['Cue\tScene\tType\tSpeaker\tVisual\tLine\tDirection\tOriginal stage direction\tComputer owners\tScreen performance\n'+text],{type:'text/tab-separated-values'}));a.download='the-big-hack-cues.tsv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.altKey||e.metaKey||e.ctrlKey)return;if(['ArrowRight','PageDown','ArrowLeft','PageUp',' ','b','B','r','R'].includes(e.key))e.preventDefault();if(['ArrowRight','PageDown'].includes(e.key))$('go').click();if(['ArrowLeft','PageUp'].includes(e.key))$('previous').click();if(e.key===' ')toggle();if(e.key.toLowerCase()==='b')blackout();if(e.key.toLowerCase()==='r')$('replay').click()});
channel.onmessage=({data})=>{if(data.type==='hello')broadcast();if(data.type==='control'){({go:()=> $('go').click(),back:()=> $('previous').click(),pause:toggle,blackout,replay:()=> $('replay').click()})[data.action]?.();}if(data.type==='heartbeat'&&!data.preview){heartbeat[data.side]=Date.now()}if(data.type==='media-error')status('Missing video: '+data.path,true)};
setInterval(()=>{broadcast();for(const side of ['left','right']){const live=Date.now()-(heartbeat[side]||0)<3500;const e=$('connection'+side[0].toUpperCase()+side.slice(1));e.textContent='● '+side[0].toUpperCase()+side.slice(1)+(live?' connected':' offline');e.style.color=live?'#c7f28b':'#c0a397'}if(timerStart){elapsedShow=Math.floor((Date.now()-timerStart)/1000);$('clock').textContent=String(Math.floor(elapsedShow/60)).padStart(2,'0')+':'+String(elapsedShow%60).padStart(2,'0')}},1000);
setInterval(()=>{if(state.running&&!audio.paused&&!audio.ended)broadcast()},250);
window.addEventListener('beforeunload',()=>{stopAudio();channel.postMessage({type:'controller-closed',controller})});
window.stage={show,get state(){return payload()},navigate,toggle,blackout,get overrides(){return overrides},get audio(){return {src:audio.getAttribute('src'),paused:audio.paused,ended:audio.ended,currentTime:audio.currentTime,duration:audio.duration}},get effects(){return sfx.map(a=>({src:a.src,paused:a.paused,loop:a.loop}))}};
renderScenes();renderRail();render();broadcast();
